---
# This playbook deploys the whole application stack in this site.

- name: Install packages
  hosts: all
  vars:
    terraform_version: 0.11.14
    golang_version: 1.13.5
  remote_user: mark

  roles:
    - common