---
# This playbook deploys the whole application stack in this site.

- name: Install packages
  hosts: all
  vars:
    terraform_version: 0.11.14
    golang_version: 1.13.5
    google_apt_file: /etc/apt/sources.list.d/google-chrome.list
    root_password_mysql: "{{ lookup('env','ROOT_PASSWORD_MYSQL') }}"
  remote_user: mark

  roles:
    - role: chaosmail.sublime-text
    - role: mysql
      become: yes
    - role: googlechrome
      become: yes
    - role: common
    - role: manala.nodejs
      become: yes
