---

- name: Adds Python MySQL support on Debian/Ubuntu
  apt: pkg="python-mysqldb" state=present

- name: Set the root password 
  mysql_user: login_user=root login_password="{{ root_password_mysql }}" user=root password="{{ root_password_mysql }}"

- name: Secure the root user for IPV6 localhost (::1)
  mysql_user: login_user=root login_password="{{ root_password_mysql }}" user=root password="{{ root_password_mysql }}" host="::1"

- name: Secure the root user for IPV4 localhost (127.0.0.1)
  mysql_user: login_user=root login_password="{{ root_password_mysql }}" user=root password="{{ root_password_mysql }}" host="127.0.0.1"

- name: Secure the root user for localhost domain
  mysql_user: login_user=root login_password="{{ root_password_mysql }}" user=root password="{{ root_password_mysql }}" host="localhost"

- name: Secure the root user for server_hostname domain
  mysql_user: login_user=root login_password="{{ root_password_mysql }}" user=root password="{{ root_password_mysql }}" host="{{ ansible_fqdn }}"

- name: Deletes anonymous server user
  mysql_user: login_user=root login_password="{{ root_password_mysql }}" user="" host_all=yes state=absent

- name: Removes the test database
  mysql_db: login_user=root login_password="{{ root_password_mysql }}" db=test state=absent