---
- name: Install Docker
  apt:
    name: docker.io
    state: present
  become: yes

- name: Make sure Docker is running
  systemd:
    state: started
    name: docker

- name: Download Terraform archive Linux 64 bits
  get_url:
    url: https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip
    dest: /tmp/terraform-{{terraform_version}}.zip

- name: Install unzip to unarchive terraform
  package:
    name: unzip
    state: present
  become: yes

- name: Unarchive Terraform archive
  unarchive:
    src: /tmp/terraform-{{terraform_version}}.zip
    dest: /tmp
    copy: no

- name: Adding terraform command to user path
  file: 
    src: /tmp/terraform
    dest: /usr/bin/terraform
    state: link
  become: yes

- name: Download Golang archive Linux 64 bits
  get_url:
    url: https://dl.google.com/go/go{{golang_version}}.linux-amd64.tar.gz
    dest: "/tmp/golang-{{golang_version}}.tar.gz"

- name: Unarchive Golang archive
  unarchive:
    src: "/tmp/golang-{{golang_version}}.tar.gz"
    dest: /tmp
    copy: no

- name: Change go executable permissions
  file:
    path: /tmp/go
    owner: root
    group: root
  become: yes

- name: Adding go command to user path
  file: 
    src: /tmp/go
    dest: /usr/local/go
    state: link
  become: yes

- name: Add GOPATH to profile
  lineinfile:
    dest: ~/.profile
    state: present
    line: 'export GOPATH=$HOME/work'

- name: Add PATH to profile
  lineinfile:
    dest: ~/.profile
    state: present
    line: 'export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin'

- name: source profile
  shell: sudo -iu {{ansible_user_id}} source ~/.profile