---
- name: Install Docker
  apt:
    name: docker.io
    state: present
  become: yes

- name: Make sure Docker is running
  systemd:
    state: started
    name: docker

- name: Download Terraform archive Linux 64 bits
  get_url:
    url: https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip
    dest: /tmp/terraform-{{terraform_version}}.zip
  vars:
    terraform_version: 0.11.14

- name: Install unzip to unarchive terraform
  package:
    name: unzip
    state: present
  become: yes

- name: Unarchive Terraform archive
  unarchive:
    src: /tmp/terraform-{{terraform_version}}.zip
    dest: "{{terraform_dir}}"
    copy: no

- name: Adding terraform command to user path
  file: 
    src: "{{terraform_dir}}/terraform"
    dest: /usr/bin/terraform
    state: link
  become: yes