---
- name: Install Docker
  apt:
    name: docker.io
    state: present
  become: yes

- name: Make sure Docker is running
  systemd:
    state: started
    name: docker

- name: Download Terraform archive Linux 64 bits
  get_url:
    url: https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip
    dest: /tmp/terraform-{{terraform_version}}.zip

- name: Install unzip to unarchive terraform
  package:
    name: unzip
    state: present
  become: yes

- name: Unarchive Terraform archive
  unarchive:
    src: /tmp/terraform-{{terraform_version}}.zip
    dest: /tmp
    copy: no

- name: Adding terraform command to user path
  file: 
    src: /tmp/terraform
    dest: /usr/bin/terraform
    state: link
  become: yes

- name: Install Visual Studio Code with snap
  snap:
    name: code
    classic: yes
  become: yes

- name: Install go with snap
  snap:
    name: go
    classic: yes
  become: yes

- name: Fetch GoLand zip
  get_url:
    url: https://download.jetbrains.com/go/goland-2019.3.tar.gz
    dest: /tmp/goland-2019.3.tar.gz
  register: goland

- name: Unarchive GoLand zip
  unarchive:
    src: /tmp/goland-2019.3.tar.gz
    dest: /tmp
  when: goland.changed

- name: Run install script for GoLand
  shell:
    cmd: /tmp/GoLand-2019.3/bin/goland.sh
  when: goland.changed

- name: Install qbittorrent
  apt:
    name: qbittorrent
    state: present
  become: yes

- name: Install VLC media player
  snap:
    name: vlc
    classic: yes
  become: yes

- name: Creates github repo directory
  file:
    path: ~/Documents/github
    state: directory

- name: Clone git repositories
  git:
    repo: "git@github.com:markvdlaan93/{{item}}.git"
    dest: "~/Documents/github/{{item}}"
  with_items:
    - "aws-terraform"
    - "markvdlaan93.github.io"
    - "avr-projects"

- name: Install Simplenote
  snap:
    name: simplenote
    classic: yes
  become: yes

- name: Make sure Snap desktop applications can be added to Gnome launcher
  file:
    src: /var/lib/snapd/desktop/applications/
    dest: /usr/share/applications/snap
    state: link
  become: yes

- name: Pin favorites in launcher
  shell: gsettings set org.gnome.shell favorite-apps "['firefox.desktop', 'org.gnome.Nautilus.desktop', 'org.gnome.Software.desktop', 'google-chrome.desktop', 'org.gnome.Terminal.desktop', 'sublime_text.desktop', 'simplenote_simplenote.desktop', 'code.desktop']"
